fix(webhooks): Correctly deserialize webhook artifacts
Before this change a webhook payload of

```json
{
  "projectId": "warpspeed-playground",
  "imageName": "dxia-spinnaker-test",
  "imageTag": "0.0.1-SNAPSHOT-20180123T195009-6b82c8e",
  "artifacts": [
    {
      "type": "docker/image",
      "name": "gcr.io/image",
      "reference": "gcr.io/image"
    }
  ]
}
```

would cause the following error.

```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.netflix.spinnaker.kork.artifacts.model.Artifact
    at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[na:1.8.0_141]
    at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) ~[na:1.8.0_141]
    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_141]
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[na:1.8.0_141]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[na:1.8.0_141]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_141]
    at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[na:1.8.0_141]
    at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[na:1.8.0_141]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_141]
    at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) ~[na:1.8.0_141]
    at com.netflix.spinnaker.echo.pipelinetriggers.artifacts.ArtifactMatcher.anyArtifactsMatchExpected(ArtifactMatcher.java:55) ~[echo-pipelinetriggers-1.544.0-SNAPSHOT.jar:1.544.0-SNAPSHOT]
    at com.netflix.spinnaker.echo.pipelinetriggers.monitor.WebhookEventMonitor.lambda$matchTriggerFor$1(WebhookEventMonitor.java:119) ~[echo-pipelinetriggers-1.544.0-SNAPSHOT.jar:1.544.0-SNAPSHOT]
```

This change correctly deserializes the JSON payload into
`List<Artifact>`.