fix(retrofit2):  fix `baseUrl must end in /` error (#1476)
* test(retrofit2): add a test to demonstrate the error: java.lang.IllegalArgumentException: baseUrl must end in /.

* fix(retrofit2): fix the following error by adding trailing / in the baseUrl and removing leading / in the end point:
java.lang.IllegalArgumentException: baseUrl must end in /.

* fix(retrofit2): fix RestService by replacing POST mapping from / to . and add a test class to demonstrate the behaviour.

Here are some references that justify this change:
https://github.com/square/retrofit/issues/907,
https://github.com/square/retrofit/issues/1701

(cherry picked from commit 19e2f34d99be5488b5cb2114b87d2cbf80a5dd3b)