fix(retrofit2): fix `A @path parameter must not come after a @Query` error (#1478)
* test(retrofit2): add a test to demonstrate the following error:
java.lang.IllegalArgumentException: A @Path parameter must not come after a @Query.

* fix(retrofit2): fix `A @Path parameter must not come after a @Query` error

(cherry picked from commit f170364c3f538d3fb867951d1a6364055ebfb450)