fix(dependency): Issue of missing javax.validation and hibernate-validator dependencies while upgrading the spring cloud to Hoxton.SR12 in kork
While upgrading spring cloud to Hoxton.SR12, we encountered below errors :

> Task :echo-rest:compileJava
/echo/echo-rest/src/main/java/com/netflix/spinnaker/echo/config/RestProperties.java:21: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
/echo/echo-rest/src/main/java/com/netflix/spinnaker/echo/config/RestProperties.java:23: error: package org.hibernate.validator.constraints does not exist
import org.hibernate.validator.constraints.NotEmpty;
                                          ^
/echo/echo-rest/src/main/java/com/netflix/spinnaker/echo/config/RestProperties.java:42: error: cannot find symbol
    @NotEmpty String url;
     ^
  symbol:   class NotEmpty
  location: class RestEndpointConfiguration
/echo/echo-rest/src/main/java/com/netflix/spinnaker/echo/config/RestProperties.java:34: error: cannot find symbol
  @Valid List<RestEndpointConfiguration> endpoints;
   ^
  symbol:   class Valid
  location: class RestProperties
4 errors

> Task :echo-rest:compileJava FAILED

=================

> Task :echo-web:compileJava FAILED
/echo/echo-web/src/main/java/com/netflix/spinnaker/echo/scheduler/ScheduledActionsController.java:30: error: package javax.validation does not exist
import javax.validation.ConstraintViolation;
                       ^
/echo/echo-web/src/main/java/com/netflix/spinnaker/echo/scheduler/ScheduledActionsController.java:31: error: package javax.validation does not exist
import javax.validation.Validation;
                       ^
/echo/echo-web/src/main/java/com/netflix/spinnaker/echo/scheduler/ScheduledActionsController.java:32: error: package javax.validation does not exist
import javax.validation.Validator;
                       ^
/echo/echo-web/src/main/java/com/netflix/spinnaker/echo/scheduler/TriggerDescription.java:3: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotBlank;
                                   ^
/echo/echo-web/src/main/java/com/netflix/spinnaker/echo/scheduler/TriggerDescription.java:8: error: cannot find symbol
  @NotBlank private String id;
   ^
  symbol:   class NotBlank
  location: class TriggerDescription
/echo/echo-web/src/main/java/com/netflix/spinnaker/echo/scheduler/TriggerDescription.java:10: error: cannot find symbol
  @NotBlank private String application;
   ^
  symbol:   class NotBlank
  location: class TriggerDescription
/echo/echo-web/src/main/java/com/netflix/spinnaker/echo/scheduler/TriggerDescription.java:12: error: cannot find symbol
  @NotBlank private String pipelineId;
   ^
  symbol:   class NotBlank
  location: class TriggerDescription
/echo/echo-web/src/main/java/com/netflix/spinnaker/echo/scheduler/TriggerDescription.java:14: error: cannot find symbol
  @NotBlank private String cronExpression;
   ^
  symbol:   class NotBlank
  location: class TriggerDescription
8 errors

FAILURE: Build failed with an exception.

The root cause is missing javax.validation:validation-api and hibernate-validator dependencies, the reason being upgrade of transitive dependency resilience4j from [1.0.0](https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-framework-common/1.0.0) to [1.7.0](https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-framework-common/1.7.0) while upgrade to Hoxton.SR12.

To fix this issue we require to explicitly implement the javax.validation dependency in gradle file of echo-rest module. And update the code import org.hibernate.validator.constraints.NotEmpty; with import javax.validation.constraints.NotEmpty; in echo-rest/src/main/java/com/netflix/spinnaker/echo/config/RestProperties.java.